#!/bin/bash
#SBATCH --account=tra24_IngInfBo
#SBATCH --partition=g100_usr_prod
#SBATCH -t 00:05:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1 # Run a single task per node
#SBATCH -c 24 # number of CPU cores i.e. OpenMP threads per task
#SBATCH -o job.out
#SBATCH -e job.err
P=8

result=$(echo "scale=10; sqrt(48*$P) + 0.5" | bc)
result=${result%.*}

echo "$result"

for I in 1 2 4 8 12 16 24 48; do
    N=$(echo "scale=10; sqrt(10000000*$I) + 0.5" | bc)
    N=${N%.*}
    echo "Launching file $I"
    ./file $N $I
done